Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -48,7 +48,7 @@ jobs:
       - name: Getting the image-tag
         id: image-tag
         run: |
-          task_definition=$(aws ecs describe-task-definition --task-definition ${{ inputs.task-name }} --query "taskDefinition.containerDefinitions[0].image" --output text 2> || echo "task-definition not found")
+          task_definition=$(aws ecs describe-task-definition --task-definition ${{ inputs.task-name }} --query "taskDefinition.containerDefinitions[0].image" --output text 2> /dev/null || echo "task-definition not found")
           if [[ task_definition == "task-definition not found" ]]; then
             image_tag=latest
             echo "image=$image_tag" >> $GITHUB_OUTPUT
